#!/bin/sh
#
# mkpasswd
#
set -euf -o pipefail
if type python3 >/dev/null 2>&1 ; then
  exec python3 $(readlink -f $0).py "$@"
elif type python >/dev/null 2>&1 ; then
  exec python $(readlink -f $0).py "$@"
else
  echo "Missing dependancies: python!" 1>&2
  exit 1
fi
