#!/bin/sh
#include prologue.sh
#
# Enrollment manager 
#
require api-enrollments.sh

[ $# -eq 0 ] && die 10 "$0: op [args]"

op="$1" ; shift


case "$op" in
list)
  if [ $# -eq 0 ] ; then
    enrolls_list | while read n
    do
      echo $(enrolls_get id "$n") $(enrolls_get dup "$n") $(enrolls_get log "$n")
    done
  fi
  ;;
help)
  cat <<-EOF
	Sub-commands:
	- $0 list : list enrollments
	EOF
  ;;
*)
  die 20 "Invalid op: $op"
  ;;
esac
