#!/bin/sh
set -euf -o pipefail
die() {
  echo "ERROR:$*" 1>&2
  exit $1
}

if [ $# -gt 0 ] ; then
  if [ x"$1" = x"--rsh" ] ; then
    shift
    if [ -n "${SSH_IP_OVERRIDE:-}" ] ; then
      exec ssh -o ProxyCommand="nc $SSH_IP_OVERRIDE %p" -i "$SSH_IDENTITY" -o BatchMode=yes "$@"
    else
      exec ssh -i "$SSH_IDENTITY" -o BatchMode=yes "$@"
    fi
    die 1 "Exec ssh failed"
  fi
fi  

verbose=""
while [ $# -gt 0 ]
do
  case "$1" in
  -v)
    verbose="v"
    ;;
  *)
    break
    ;;
  esac
  shift
done


[ $# -eq 0 ] && die 2 "Usage: [SSH_IP_OVERRIDE=xx] [SSH_IDENITY=file] $0 (target)"

cmd=$(readlink -f "$0")
target="$1"

rsync -az${verbose} --exclude='*~' --delete --rsh="$cmd --rsh" "$TLR_HOME/" "$target":"$TLR_HOME"
"$cmd" --rsh "$target" "$TLR_SCRIPTS/apply_policies"


